version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8000:8000"
    depends_on:
      - app

volumes:
  static_data:
